controller_manager:
  ros__parameters:
    use_sim_time: false       # <— key fix: don’t wait on /clock
    update_rate: 1000         # match sim (1 ms)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters: {}

position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - "Revolute 77"
      - "Revolute 78"
      - "Revolute 79"
      - "Revolute 80"
      - "Revolute 90"
      - "Revolute 91"
      - "Revolute 92"
      - "Revolute 93"
      - "Revolute 102"
      - "Revolute 103"
      - "Revolute 104"
      - "Revolute 105"
